AcmeHelloBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller:AcmeHelloBundle:Hello:index, name: someone}
    #requirements:
        #name:  leo|Leo

_create:
    pattern:  /create
    defaults: { _controller:AcmeHelloBundle:Hello:create}
    
_add:
    pattern: /add
    defaults: {_controller:AcmeHelloBundle:Hello:add}