<?php

namespace Acme\HelloBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findAllOrderByName()
    {
        return $this->getEntityManager()
            ->createQuery('
                          SELECT p
                          FROM AcmeHelloBundle:Product p
                          ORDER BY p.name
                          ')
            ->getResult();
    }
    
    public function findSpecificOrderByName($shortcode) {
        return $this->getEntityManager()
            ->createQuery('
                          SELECT p
                          FROM AcmeHelloBundle:Product p
                          WHERE p.shortcode = :shortcode
                          ORDER BY p.name
                          ')
            ->setParameter('shortcode', $shortcode)
            ->getResult();
    }
    
    public function findAllInfoSpecificProductById($id) {
        $query = $this->getEntityManager()
            ->createQuery('
                          SELECT
                            p
                          FROM
                            AcmeHelloBundle:Product p JOIN p.tag t
                          WHERE
                            p.id = :id
                          ')
            ->setParameter('id', $id);
            
        try{
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
        
    }
    
}