<?php

namespace Acme\HelloBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CampaignTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignTagRepository extends EntityRepository
{
}